# Generated by Django 3.1.2 on 2020-10-10 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('planted_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True)),
                ('estimated_cost', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=48)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('activities', models.TextField(blank=True)),
                ('method', models.TextField(blank=True)),
                ('cost', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=48)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listing')),
            ],
        ),
    ]
