# Generated by Django 3.1.2 on 2020-10-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201012_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrecord',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='main.listing'),
        ),
    ]
