# Generated by Django 3.1.2 on 2020-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201012_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsCartegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landprep', models.CharField(max_length=50)),
                ('deseasecon', models.CharField(max_length=50)),
                ('havest', models.CharField(max_length=50)),
                ('planting', models.CharField(max_length=50)),
                ('weeding', models.CharField(max_length=50)),
                ('fartiliser', models.CharField(max_length=50)),
                ('pruning', models.CharField(max_length=50)),
                ('staking', models.CharField(max_length=50)),
                ('pestcontrol', models.CharField(max_length=50)),
            ],
        ),
    ]
