# Generated by Django 3.1.2 on 2020-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201018_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourer',
            name='allproj',
            field=models.ManyToManyField(blank=True, to='main.Listing'),
        ),
    ]
